Add database columns to jobs for W3C trace context
divviup/janus pull request #1800
Opened 2023-08-24 19:40 UTC by divergentdave

This adds `jsonb` database columns to aggregation jobs and collection jobs to propagate distributed tracing metadata through our job queue system. This is part of #1628.

2023-08-24 20:30 UTC, tgeoghegan approved these changes

2023-08-24 21:37 UTC, branlwyd requested changes
As this is on `main` for an as-yet-unreleased version, the schema change should be phrased as a change to the `initial_schema` script rather than a migration.

2023-08-25 18:38 UTC, branlwyd approved these changes

2023-08-25 18:41 UTC, branlwyd commented
(the label might be too late unless you want to try pushing again, poke me if you'd like me to merge.)

2023-08-25 19:08 UTC, merged