Relax constraints on bearer token format
divviup/janus pull request #3111
Opened 2024-05-08 20:34 UTC by inahga

Closes https://github.com/divviup/janus/issues/3107. The `bearer` part is now case insensitive. Add some basic tests.

I also allow whitespace between `bearer` and the token. The `1*SP` part of the grammar, IIUC, indices one or more whitespace:
```
Authorization = credentials
credentials = auth-scheme [ 1*SP ( token68 / #auth-param ) ]
```

2024-05-08 20:43 UTC, divergentdave approved these changes

2024-05-08 21:04 UTC, branlwyd approved these changes

2024-05-09 00:13 UTC, tgeoghegan requested changes

2024-05-09 00:13 UTC, tgeoghegan commented on core/src/http.rs
> +        if bearer.to_lowercase() != "bearer" {
nit:
```suggestion
        let (auth_scheme, token) = authorization
            .split_once(char::is_whitespace)
            .ok_or_else(|| anyhow!("invalid scheme in authorization header"))?;

        if auth_scheme.to_lowercase() != "bearer" {
```


To line up with the `credentials = auth-scheme [ 1*SP ( token68 / #auth-param ) ]` in the Backaus-whatever notation.

2024-05-09 00:13 UTC, tgeoghegan commented on core/src/http.rs
> +            Ok(Some(_))
I think it'd be nice to check the contents of the `AuthenticationToken` to make sure nothing bad happens when we call `String::trim_start`.

2024-05-09 16:54 UTC, tgeoghegan approved these changes

2024-05-09 16:55 UTC, merged