Add a length prefix to public_share in AAD
divviup/janus pull request #701
Opened 2022-10-31 19:40 UTC by divergentdave

This adds a length prefix in our input share AAD construction, to match Daphne's interpretation. See https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/371 for discussion of related spec changes.

2022-10-31 20:35 UTC, tgeoghegan approved these changes

2022-11-01 16:24 UTC, branlwyd requested changes
(I think this PR should not be merged for the reason above.)

2022-11-30 21:21 UTC, divergentdave commented
The DAP specification has been updated to make this length prefix explicitly required, and we're now targeting DAP-03 on the main branch, so I think this should be good to go now.

2022-11-30 22:31 UTC, branlwyd approved these changes

2022-11-30 22:47 UTC, merged