Store batch ID in leader aggregation jobs to speed up collect_job_driver queries
divviup/janus pull request #758
Opened 2022-11-17 19:21 UTC by divergentdave

This implements one of the ideas from #519, tracking the non-partial batch identifier for leader aggregation jobs. This adds two nullable database columns; like in `collect_jobs`, we store the serialized batch identifier for general use, plus a `tsrange` copy for time interval tasks, so we can index on it and check range containment in database queries.

Tests pass with the updated query, but I haven't yet looked at query plans or tried it out in a stress test.

2022-11-18 20:44 UTC, divergentdave commented
Here's an apples-to-apples query plan against one task, 17000 aggregation jobs, and 105 collect jobs. Skipping the client_reports/report_aggregations tables is a huge win.

```
                                                                                         QUERY PLAN                                                                                         
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=54639.10..54639.23 rows=52 width=160) (actual time=31.748..31.750 rows=0 loops=1)
   Sort Key: updated.id DESC
   Sort Method: quicksort  Memory: 25kB
   CTE updated
     ->  Update on collect_jobs collect_jobs_1  (cost=0.00..54636.58 rows=52 width=111) (actual time=31.707..31.709 rows=0 loops=1)
           ->  Nested Loop  (cost=0.00..54636.58 rows=52 width=111) (actual time=31.705..31.707 rows=0 loops=1)
                 Join Filter: (SubPlan 1)
                 Rows Removed by Join Filter: 105
                 ->  Seq Scan on tasks  (cost=0.00..1.01 rows=1 width=65) (actual time=0.006..0.007 rows=1 loops=1)
                 ->  Seq Scan on collect_jobs collect_jobs_1  (cost=0.00..3.05 rows=105 width=22) (actual time=0.007..0.021 rows=105 loops=1)
                 SubPlan 1
                   ->  Limit  (cost=5.08..1035.50 rows=5 width=8) (actual time=0.301..0.301 rows=0 loops=105)
                         ->  GroupAggregate  (cost=5.08..1035.50 rows=5 width=8) (actual time=0.301..0.301 rows=0 loops=105)
                               Group Key: collect_jobs.id
                               Filter: bool_and((aggregation_jobs.state <> 'IN_PROGRESS'::aggregation_job_state))
                               Rows Removed by Filter: 10
                               ->  Nested Loop  (cost=5.08..1034.13 rows=170 width=12) (actual time=0.030..0.299 rows=10 loops=105)
                                     ->  Index Scan using collect_jobs_pkey on collect_jobs  (cost=0.14..15.51 rows=10 width=39) (actual time=0.002..0.016 rows=10 loops=105)
                                           Filter: ((lease_expiry <= '2022-11-17 00:00:00'::timestamp without time zone) AND (task_id = tasks.id) AND (state = 'START'::collect_job_state))
                                           Rows Removed by Filter: 95
                                     ->  Bitmap Heap Scan on aggregation_jobs  (cost=4.93..101.01 rows=85 width=35) (actual time=0.028..0.028 rows=1 loops=1050)
                                           Recheck Cond: (collect_jobs.batch_interval @> batch_interval)
                                           Filter: ((task_id = tasks.id) AND (collect_jobs.aggregation_param = aggregation_param))
                                           Heap Blocks: exact=1050
                                           ->  Bitmap Index Scan on aggregation_jobs_batch_interval  (cost=0.00..4.91 rows=85 width=0) (actual time=0.027..0.027 rows=1 loops=1050)
                                                 Index Cond: (batch_interval <@ collect_jobs.batch_interval)
   ->  CTE Scan on updated  (cost=0.00..1.04 rows=52 width=160) (actual time=31.709..31.709 rows=0 loops=1)
 Planning Time: 1.225 ms
 Execution Time: 32.520 ms
```

I did some further testing and found that this revised query hits a wall when the number of collect jobs is large. For example, with 100,000 collect jobs, across 100 tasks, the plan costs are far too high, and the query takes impractically long to run. This isn't the end of the story for #519, but it does buy us several orders of magnitude.

I'll plan to rebase this after #759 lands before marking it ready for review.

2022-11-21 18:14 UTC, branlwyd requested changes

2022-11-21 19:03 UTC, divergentdave commented on aggregator/src/aggregator.rs
> +        Q: AccumulableQueryType + CollectableQueryType,
Currently `Transaction::put_aggregation_job()` requires the `CollectableQueryType` trait, for its `to_batch_interval()` method, converting a `BatchIdentifier` to an `Interval`. In this code path, the identifier is `None`, but we need the trait bound nevertheless. Shuffling the method over sounds good to me.

2022-11-21 19:37 UTC, divergentdave commented on aggregator/src/datastore.rs
> +        pub fn batch_identifier(&self) -> &Option<Q::BatchIdentifier> {
I think that can work, but as we'll just have one nullable column, we'll have to do some additional validation in the datastore module.

Here are the different possibilities spelled out, both for the code as written, and with only one column.

|Role|Query|partial_batch_identifier|batch_identifier|Unified column|
|---|---|---|---|---|
|Leader|Time interval|Empty string|16 bytes|16 bytes|
|Leader|Fixed size|32 bytes|32 bytes|32 bytes|
|Helper|Time interval|Empty string|NULL|NULL|
|Helper|Fixed size|32 bytes|NULL|32 bytes|

Note that the `partial_batch_identifier` column differs for time interval query types. The method `AggregationJob::<TimeInterval, ...>::partial_batch_identifier()` will have to return the unit type regardless of the column's value.

2022-11-23 14:52 UTC, merged