store helper's `A::PrepareShare` in the database
divviup/janus pull request #911
Opened 2023-01-14 01:27 UTC by tgeoghegan

# Stacked on #910 

DAP-04 introduces protocol affordances for recovering from round skew. To that end, the helper needs to store the prepare shares from its current round so that it can service replayed aggregation job continuation requests from the leader.

---

I'm working on the changes needed to implement DAP-04 in https://github.com/divviup/janus/pull/731. Since DAP-04 isn't ready yet and in order to reduce the size of the eventual PR wiring up the new HTTP API, I'm teasing out some independent pieces into more digestible PRs.

This is the first change that we might not want to take into our DAP-03 implementation: there's no reason for the helper to store prepare shares until DAP-04, so this would just use more storage space for no benefit. Therefore we might want to branch `release/0.3` from `main` before taking this change.

2023-01-17 20:49 UTC, branlwyd requested changes
cjpatton requested that the recovery functionality be pulled out to a different spec PR; due to that, and the fact that we don't need this functionality until DAP-04, let's wait to merge.

2023-01-19 17:55 UTC, tgeoghegan commented
Downgrading to draft while we sort out the corresponding protocol changes.

2023-03-08 20:10 UTC, tgeoghegan commented
I've resumed working on #994, so it's time to dust off this change

2023-03-09 17:12 UTC, branlwyd approved these changes

2023-03-09 18:11 UTC, divergentdave approved these changes

2023-03-09 18:11 UTC, divergentdave commented on db/schema.sql
> +                                                            -- for the helper, the next preparation share to be sent to the leader (opaque VDAF message)
Could we spell out in which states this should be non-NULL? (is it when in the `WAITING` state for both leader and helper cases?)

2023-03-09 19:01 UTC, merged